"""Branch summary and release notes generation.

Rule-based natural language summaries generated from commit history.
Designed to also serve as an integration point for LLM-based summarization.
"""

from __future__ import annotations

from collections import Counter


def generate_branch_summary(
    branch_name: str,
    commits: list[dict],
) -> str:
    """Generate a natural-language summary of a branch's activity.

    Args:
        branch_name: The branch name.
        commits: List of commit dicts with 'b', 's', 't' fields.
            Only commits where branch_name is in 'b' are included.

    Returns:
        A short, human-readable summary string.
    """
    # Filter commits on this branch
    branch_commits: list[dict] = []
    for c in commits:
        b = c.get("b", [])
        if branch_name in b:
            branch_commits.append(c)

    if not branch_commits:
        return f"'{branch_name}' has no commits."

    n = len(branch_commits)

    # Categorize commits by type
    feat_count = 0
    fix_count = 0
    refactor_count = 0
    doc_count = 0
    chore_count = 0
    merge_count = 0

    authors: Counter = Counter()

    for c in branch_commits:
        s = c.get("s", "").lower()
        a = c.get("a", "")
        if a:
            authors[a] += 1

        if s.startswith("feat") or s.startswith("feature"):
            feat_count += 1
        elif s.startswith("fix") or s.startswith("bugfix") or s.startswith("hotfix"):
            fix_count += 1
        elif s.startswith("refactor"):
            refactor_count += 1
        elif s.startswith("doc") or s.startswith("docs"):
            doc_count += 1
        elif s.startswith("merge"):
            merge_count += 1
        elif s.startswith("chore") or s.startswith("ci") or s.startswith("test"):
            chore_count += 1

    # Compute date range
    dates = []
    for c in branch_commits:
        t = c.get("t", "")
        if t:
            dates.append(t[:10])

    date_range = ""
    if dates:
        dates.sort()
        date_range = f"{dates[0]} to {dates[-1]}"

    # Build summary
    parts = [f"{n} commits"]
    if feat_count:
        parts.append(f"{feat_count} feat")
    if fix_count:
        parts.append(f"{fix_count} fix")
    if refactor_count:
        parts.append(f"{refactor_count} refactor")
    if doc_count:
        parts.append(f"{doc_count} docs")
    if chore_count:
        parts.append(f"{chore_count} chore/ci/test")
    if merge_count:
        parts.append(f"{merge_count} merge")

    top_author = authors.most_common(1)
    summary = f"{n} commits: " + ", ".join(parts) + f" by {len(authors)} author(s)"
    if top_author:
        summary += f" (led by {top_author[0][0]})"
    if date_range:
        summary += f" — {date_range}"

    return summary


def generate_release_notes(
    branches: list[dict],
    health_list: list[dict],
) -> str:
    """Generate a release notes draft from branch data.

    Groups branches by type (features, fixes, chores) and generates a
    structured changelog.

    Returns:
        Markdown-formatted release notes string.
    """
    # Build health lookup
    health_lookup: dict[str, dict] = {h.get("n", ""): h for h in health_list}

    features: list[str] = []
    fixes: list[str] = []
    other: list[str] = []
    merged_branches: list[str] = []

    for b in branches:
        name = b.get("n", "")
        k = b.get("k", "")
        if k != "local":
            continue
        h = health_lookup.get(name, {})
        mg = h.get("mg", False)
        st = h.get("st", "")

        if mg or st == "zombie_merged":
            merged_branches.append(name)
            bt = h.get("bt", "other")
            if bt == "feature":
                features.append(name)
            elif bt in ("hotfix", "release"):
                fixes.append(name)
            else:
                other.append(name)

    lines = ["## Release Notes (auto-generated)\n"]
    lines.append(f"*{len(merged_branches)} merged branches included.*\n")

    if features:
        lines.append("### Features")
        for f in features:
            lines.append(f"- [{f}](#)")
        lines.append("")

    if fixes:
        lines.append("### Fixes & Hotfixes")
        for f in fixes:
            lines.append(f"- [{f}](#)")
        lines.append("")

    if other:
        lines.append("### Other Changes")
        for f in other:
            lines.append(f"- [{f}](#)")
        lines.append("")

    lines.append("*Generated by git-graph*")
    return "\n".join(lines)
